# Fastfile for Flutter iOS CI/CD

org, repo = (ENV["GITHUB_REPOSITORY"] || "").split("/")
match_org, match_repo = (ENV["MATCH_REPOSITORY"] || "").split("/")

platform :ios do
  
  #########################################################
  # Init CI (creates proper temporary keychain)
  #########################################################
  lane :init_ci do
    github_action(
      api_token: ENV["GH_PAT"],
      org: org,
      repo: repo,
      match_org: match_org,
      match_repo: match_repo,
      writable_deploy_key: true
    )
  end
  
  #########################################################
  # Sync codesigning certificates
  #########################################################
  desc "Sync codesigning certificates"
  lane :sync_certificates do
    api_key = app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_content: ENV['APPSTORE_P8']
    )

    main_app_bundle_id = ENV["IOS_BUNDLE_ID"]
    extension_bundle_id = "#{main_app_bundle_id}.notifications"

    match(
      type: "appstore",
      storage_mode: "git",
      git_url: "git@github.com:#{match_org}/#{match_repo}.git",
      app_identifier: [main_app_bundle_id, extension_bundle_id],
      api_key: api_key
    )
  end

  #########################################################
  # Build and upload to TestFlight
  #########################################################
  desc "Build and upload to TestFlight"
  lane :beta do
    setup_ci
    sync_certificates

    ###########################################
    # Prepare ExportOptions.plist
    ###########################################
    export_options_path = File.expand_path("../ios/ExportOptions.plist", __dir__)

    main_profile = ENV["sigh_#{ENV['IOS_BUNDLE_ID']}_appstore_profile-name"]
    extension_profile = ENV["sigh_#{ENV['IOS_BUNDLE_ID']}.notifications_appstore_profile-name"]

    require 'plist'
    export_options = Plist.parse_xml(export_options_path)

    if export_options.nil?
      UI.message("ExportOptions.plist missing or invalid. Creating minimal config.")
      export_options = {
        'method' => 'app-store',
        'teamID' => ENV['APPLE_TEAM_ID'],
        'provisioningProfiles' => {}
      }
    end

    export_options['method'] = 'app-store'
    export_options['teamID'] = ENV['APPLE_TEAM_ID']

    export_options['provisioningProfiles'] = {
      ENV['IOS_BUNDLE_ID'] => main_profile,
      "#{ENV['IOS_BUNDLE_ID']}.notifications" => extension_profile
    }

    File.write(export_options_path, export_options.to_plist)

    ###########################################
    # Safe build number
    ###########################################
    build_number = Time.now.to_i.to_s
    UI.message("Using build number: #{build_number}")

    ###########################################
    # Clean & Build
    ###########################################
    sh "flutter clean"
    sh "flutter pub get"

    project_root = File.expand_path("..", __dir__)
    ios_path = File.join(project_root, "ios")

    sh "pod install --repo-update", chdir: ios_path

    sh """
      flutter build ipa \
        --release \
        --export-options-plist=#{export_options_path} \
        --build-number=#{build_number} \
        --no-tree-shake-icons
    """

    ###########################################
    # Upload IPA
    ###########################################
    ipa_path = Dir.glob(File.expand_path("../build/ios/ipa/*.ipa", __dir__)).first
    UI.user_error!("No IPA file found at build/ios/ipa/") unless ipa_path

    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      ipa: ipa_path
    )
  end

end
