# Fastfile for Flutter iOS CI/CD

opt_out_usage

org, repo = (ENV["GITHUB_REPOSITORY"] || "").split("/")
match_org, match_repo = (ENV["MATCH_REPOSITORY"] || "").split("/")

platform :ios do

  #########################################################
  # Init CI (temporary keychain for GitHub Actions)
  #########################################################
  lane :init_ci do
    github_action(
      api_token: ENV["GH_PAT"],
      org: org,
      repo: repo,
      match_org: match_org,
      match_repo: match_repo,
      writable_deploy_key: true
    )
  end

  #########################################################
  # Sync certificates using Match
  #########################################################
  desc "Sync codesigning certificates"
  lane :sync_certificates do
    api_key = app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_content: ENV["APPSTORE_P8"]
    )

    main_bundle = ENV["IOS_BUNDLE_ID"]
    extension_bundle = "#{main_bundle}.notifications"

    match(
      type: "appstore",
      storage_mode: "git",
      git_url: "git@github.com:#{match_org}/#{match_repo}.git",
      app_identifier: [main_bundle, extension_bundle],
      api_key: api_key
    )
  end

  #########################################################
  # Build and upload to TestFlight
  #########################################################
  desc "Build and upload to TestFlight"
  lane :beta do
    setup_ci
    sync_certificates

    project_root = File.expand_path("..", __dir__)
    ios_path = File.join(project_root, "ios")
    build_path = File.join(project_root, "build")

    #######################################################
    # Prepare ExportOptions.plist
    #######################################################
    export_options_path = File.join(ios_path, "ExportOptions.plist")

    main_profile = ENV["sigh_#{ENV['IOS_BUNDLE_ID']}_appstore_profile-name"]
    extension_profile = ENV["sigh_#{ENV['IOS_BUNDLE_ID']}.notifications_appstore_profile-name"]

    require 'plist'
    export_options = File.exist?(export_options_path) ? Plist.parse_xml(export_options_path) : nil

    if export_options.nil?
      UI.message("Creating minimal ExportOptions.plist")
      export_options = {
        'method' => 'app-store',
        'teamID' => ENV['APPLE_TEAM_ID'],
        'provisioningProfiles' => {}
      }
    end

    export_options['method'] = 'app-store'
    export_options['teamID'] = ENV['APPLE_TEAM_ID']
    export_options['provisioningProfiles'] = {
      ENV['IOS_BUNDLE_ID'] => main_profile,
      "#{ENV['IOS_BUNDLE_ID']}.notifications" => extension_profile
    }

    File.write(export_options_path, export_options.to_plist)

    #######################################################
    # Safe build number (unique)
    #######################################################
    build_number = Time.now.to_i.to_s
    UI.message("Using build number: #{build_number}")

    #######################################################
    # Clean & Build
    #######################################################
    sh "flutter clean", chdir: project_root
    sh "flutter pub get", chdir: project_root

    sh "flutter build ipa --release --export-options-plist=#{export_options_path} --build-number=#{build_number} --no-tree-shake-icons", chdir: project_root

    #######################################################
    # Find IPA
    #######################################################
    ipa_path = Dir.glob(File.join(build_path, "ios/ipa/*.ipa")).first
    UI.user_error!("No IPA file found at build/ios/ipa/") unless ipa_path

    #######################################################
    # Upload to TestFlight using API key
    #######################################################
    api_key = app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_content: ENV["APPSTORE_P8"]
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      ipa: ipa_path,
      api_key: api_key
    )
  end

end
